services:
  web:
    image: nginx:latest
    container_name: nginx-jnvctf
    ports:
      - "8042:80"
    volumes:
      - ./www:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    restart: always

  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm-jnvctf
    volumes:
      - ./www:/var/www/html
    ports:
      - "9000:9000"
    restart: always